[package]
name = "chess-pgn-reviser"
version = "0.1.0"
authors = ["Laurent Bernabe <laurent.bernabe@gmail.com>"]
edition = "2018"

[dependencies]
relm = "0.20.0"
relm-derive = "0.20.0"
gtk = "0.9.0"
gdk = "0.13.0"
glib = "0.10.0"
cairo-rs = "0.9.0"
pleco = "0.5.0"
nsvg = "0.5.1"